baseURL = "https://tamada.github.io/sibling"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Sibling"
enableEmoji = true
theme = "cayman-hugo-theme"
googleAnalytics = ""

pygmentsCodefences = true
pygmentsStyle = "pygments"

[params]
    project_name = "sibling"
    project_logo = "images/folders.svg"
    project_tagline = "get next/previous sibling directory name"
    dateFormat = "2006-01-02"
    katex = true
    version = "1.2.2"
    footer = "[![GitHub](https://img.shields.io/badge/GitHub-tamada/sibling-blueviolet.svg?logo=github)](https://github.com/tamada/sibling) Made with [Hugo](https://gohugo.io/). Theme by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [GitHub Pages](https://pages.github.com/)."

[menu]
    [[menu.nav]]
        name = ":house: Home"
        url = "/"
        weight = 10
    [[menu.nav]]
        name = ":anchor: Install"
        url = "/install"
        weight = 20
    [[menu.nav]]
        name = ":runner: Usage"
        url = "/usage"
        weight = 30
    [[menu.nav]]
        name = ":smile: About"
        url = "/about"
        weight = 50